In [63]:
import numpy as np

import ground_truth as gt

In [64]:
np.random.seed(0)
N = 8
K = 2

x = gt.get_x_vector(N, K)

In [65]:
true_W_hat = gt.get_true_W_hat(N, K, x)
print(f'True scalar value: {gt.scalar(true_W_hat @ x)}\n')
print(f'True W_hat: \n{true_W_hat}')

x = [0. 0. 1. 0. 0. 0. 1. 0.]
Scalar value = 8
True scalar value: 8

True W_hat: 
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1. 0. 0. 1.]]


In [79]:
W_hat = gt.gen_W_hat(N)
W = np.array([gt.get_w_hat_t(i, N) for i in range(N)])
to_remove = gt.get_W_hat_rows(W, W_hat)
W = np.delete(W, to_remove, 0)

# Sample a random remaining row from W
rand_idx = np.random.choice(np.arange(0, len(W)), 1, replace=False)[0]

W_hat = np.append(W_hat, [W[rand_idx]], 0)

print(np.all(W_hat == true_W_hat))
gt.scalar(W_hat @ x)

False


16